import mongoose from "mongoose";

/**
 * invoiceModel.js
 * --------------------------------------
 * A SEPARATE collection — does NOT touch tourBookingModel at all.
 *
 * One document per booking, created/updated only when an admin edits and
 * saves an invoice. If no document exists here for a given TNR, the
 * invoice is just built fresh (auto-calculated) as before.
 *
 * ── sourceRef ────────────────────────────────────────────────────────────
 * Every item/payment carries an optional `sourceRef`:
 *   - present  → this entry was auto-generated by buildInvoiceView
 *                (base sharing-group item, admin-remark-derived item,
 *                advance/balance payment, negative-remark payment).
 *                tourController.js's syncInvoiceWithBooking() ALWAYS
 *                regenerates these fresh from the live booking on every
 *                GET, so new/edited/removed remarks show up automatically.
 *   - absent   → this entry was manually added by the admin via
 *                "+ Add Item" / "+ Add Payment" in the invoice editor.
 *                These are preserved untouched forever.
 *
 * billedTo, purchaseDate, dueDate, tourCode, billedBy, and totals.roundOff
 * are always treated as manual/editable and are kept from the saved doc
 * as-is (see syncInvoiceWithBooking).
 */

const invoiceItemSchema = new mongoose.Schema(
  {
    description: { type: String, required: true },
    subDescription: { type: String },
    sourceRef: { type: String, default: null },
    gstRate: { type: Number, default: 0 },
    quantity: { type: Number, required: true },
    rate: { type: Number, required: true },
    amount: { type: Number, required: true },
    cgst: { type: Number, default: 0 },
    sgst: { type: Number, default: 0 },
    total: { type: Number, required: true },
  },
  { _id: false },
);

const paymentEntrySchema = new mongoose.Schema(
  {
    date: { type: Date },
    amountReceived: { type: Number, required: true },
    sourceRef: { type: String, default: null },
  },
  { _id: false },
);

const invoiceSchema = new mongoose.Schema(
  {
    // Link back to the booking — one invoice document per booking.
    tnr: {
      type: String,
      unique: true,
      required: true,
      trim: true,
      uppercase: true,
    },
    bookingId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "tourBooking",
      required: true,
    },

    invoiceNumber: { type: String, required: true },
    purchaseDate: { type: Date },
    dueDate: { type: Date }, // trip start date (tour.lastBookingDate)
    tourCode: { type: String }, // shows the tour NAME (see buildInvoiceView)

    billedBy: {
      companyName: { type: String },
      addressLine1: { type: String },
      city: { type: String },
      state: { type: String },
      country: { type: String },
      pincode: { type: String },
      gstin: { type: String },
      pan: { type: String },
      tan: { type: String },
      phone: { type: String },
    },

    billedTo: {
      name: { type: String },
      addressLine1: { type: String },
      addressLine2: { type: String },
      city: { type: String },
      state: { type: String },
      country: { type: String },
      pincode: { type: String },
      phone: { type: String },
    },

    countryOfSupply: { type: String, default: "India" },
    placeOfSupply: { type: String },

    items: [invoiceItemSchema],

    totals: {
      amount: { type: Number, required: true },
      cgst: { type: Number, default: 0 },
      sgst: { type: Number, default: 0 },
      roundOff: { type: Number, default: 0 },
      grandTotal: { type: Number, required: true },
    },

    payments: [paymentEntrySchema],
    amountPaid: { type: Number, default: 0 },
    dueAmount: { type: Number, default: 0 },
    deletedSourceRefs: { type: [String], default: [] },   // ← ADD THIS


    status: {
      type: String,
      enum: ["Part Paid", "Paid"],
      default: "Part Paid",
    },

    // Who/when it was last edited (optional, but useful for an audit trail)
    lastEditedAt: { type: Date, default: Date.now },
  },
  { timestamps: true },
);

// Keep status/dueAmount consistent automatically on every save
invoiceSchema.pre("save", function (next) {
  this.dueAmount = Math.max(
    0,
    Number((this.totals.grandTotal - this.amountPaid).toFixed(2)),
  );
  this.status = this.dueAmount <= 0 ? "Paid" : "Part Paid";
  this.lastEditedAt = new Date();
  next();
});

const invoiceModel =
  mongoose.models.invoice || mongoose.model("invoice", invoiceSchema);

export default invoiceModel;